name: Lint Checking

on:
  push:
    branches: [training/cicd_pipeline]
    paths:
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*
  pull_request:
    branches: [training/cicd_pipeline]

jobs:
  android-lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    # container: "To be questioned"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run Yaml Lint
        id: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*values*.yaml
          config_file: .yamllint.yml
          strict: true
          no_warnings: true
        continue-on-error: false
      - name: SetUp JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Run Project Lint
        run: ./gradlew lint
        continue-on-error: false


  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: set up JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: zulu
  #         java-version: 17

  #     - name: Cache Gradle and wrapper
  #       uses: actions/cache@v4
  #       with:
  #         path: |
  #           ~/.gradle/caches
  #           ~/.gradle/wrapper
  #         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gradle-

  #     - name: Make Gradle executable
  #       run: chmod +x ./gradlew

  #     - name: Build with Gradle
  #       run: ./gradlew build
