name: Unit-Testing

on:
 push:
  branches: [training/cicd_pipeline]

jobs:
 run-unit-test:
  name: Run Unit Tests
  runs-on: ubuntu-latest
  timeout-minutes: 100
  steps:
   - name: "Checkout Repo"
     uses: actions/checkout@v4
     with:
      submodules: true
   - name: SetUp JDK
     uses: actions/setup-java@v4
     with:
      distribution: 'temurin'
      java-version: 21
      cache: gradle
   - name: Android Unit Test
     run: ./gradlew testDebugUnitTest
   - name: Android Unit Test
     uses: asadmansr/android-test-report-action@v1.2.0
     if: ${{ always() }}
     