name: Unit-Testing

on:
 push:
  branches: [training/cicd_pipeline]

jobs:
 run-unit-test:
  name: Run Unit Tests
  runs-on: ubuntu-latest
  timeout-minutes: 100
  steps:
   - name: "Checkout Repo"
     uses: actions/checkout@v4
     with:
      submodules: true
   - name: Android Github Action
     uses: vukan-markovic/Github-Android-Action@1.2
