name: Create Dev Staging Environment
'on':
  workflow_dispatch:
    inputs:
      PR_Number:
        description: Pull request no
        required: true
jobs:
  create:
    name: Create Staging and Deploy
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR no
        uses: actions/github-script@v7
        id: verify_id_no
        with:
          github-token: ${{ secrets.DEPLOY_SECRET }}
          result-encoding: string
          script: |
            const response = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ github.event.inputs.PR_Number }}
            });

            //Check if PR is open, otherwise, throw error
            if (response.data.number !== ${{ github.event.inputs.PR_Number }}){
                throw new Error("PR is not open or number is not correct");
            }

            console.log("PR ref/branch name: "+ response.data.head.ref);
            return response.data.head.ref;
      - name: Checkout the branch
        uses: actions/checkout@v4
        with:
          ref: '${{ steps.verify_id_no.outputs.result }}'
      - name: Deploy to Staging
        run: echo "Deploying..."
      - name: Update status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEPLOY_SECRET }}
          script: |
            const output = `#### Staging created
            > PR #${{ github.event.inputs.PR_Number }} has been deployed

            URL: [path to the build] `;

            github.rest.issues.createComment({
                issue_number: ${{ github.event.inputs.PR_Number }},
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
            })
